# README Generator Configuration
generator:
  template_file: "./readme_generation/README.template"
  output_file: "README.md"
  data_directory: "./readme_generation/data"
  
# Define the order and optional nature of sections
sections:
  - name: "title"
    file: "title.yaml"
    required: true
  - name: "built_with"
    file: "built_with.yaml"
    required: false
  - name: "features"
    file: "features.yaml"
    required: false
  - name: "install"
    file: "install.yaml"
    required: false
  - name: "usage"
    file: "usage.yaml"
    required: false
  - name: "project_structure"
    file: "project_struture.yaml"
    required: false
  - name: "security_and_privacy"
    file: "security_and_privacy.yaml"
    required: false
  - name: "troubleshooting"
    file: "troubleshooting.yaml"
    required: false
  - name: "license"
    file: "license.yaml"
    required: false
  - name: "roadmap"
    file: "roadmap.yaml"
    required: false
  - name: "contributing"
    file: "contributing.yaml"
    required: false
  - name: "contact"
    file: "contact.yaml"
    required: false
  - name: "sources"
    file: "sources.yaml"
    required: false
  - name: "link"
    file: "link.yaml"
    required: false

# Validation rules
validation:
  check_placeholders: true
  strict_mode: false  # If true, all placeholders must have values
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s" 