# src/logger/logger_config.yaml

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: ./logs/app.log
      mode: a
  loggers:
    default:
      level: DEBUG
      handlers: [console]
    ElasticsearchEngine:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    BeautifulSoupEngine:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    JobScraper:
      level: DEBUG
      handlers: [console, file]
      propagate: no